### ISSUE TITLE
The variable diacritics lacks some elements

### ISSUE THREAD

**Issue by mtrevisan** [dannytheliar/phonologizer#2]
The variable diacritics lacks the following elements:

```
var diacritics = {
   ...
   '\u031D': [{...}, {...}, 'raised'],
   '\u031E': [{...}, {...}, 'lowered'],
   '\u033A': [{...}, {...}, 'apical'],
   '\u033B': [{...}, {...}, 'laminal']
};
```

What I'm asking you is if you can provide the code for the missing elements.
Thank you

**Comment by dannytheliar** [comment]
The specific feature set I used was adapted from the source of Bruce Hayes' [FeaturePad](http://www.linguistics.ucla.edu/people/hayes/120a/FeaturePad.htm),  which doesn't include those particular diacritics. I can't confidently produce data that'd be congruent with this analysis.

If you want to take a crack at it, the first item is the feature bundle set by the diacritic, and the second is, in fact, unused.
